# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b364c3f726f0a6b3bf83ba12a28a41eb090da855f5650d7ebc01770e263c36749d69574abbc045c95468888a20068047e9cad8d2d303e6311f316a5e0449c93c

test:
  secret_key_base: 3e1119b065d147b2d0c4f2d892ae7d3f9d806b283e41fb82df4034abe1d547c03e14b01d63e75065270213da5608cdabdf65fa40a4b4de6bc94b32d514aaeabd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
